### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  23 & 26 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [47]:
import numpy as np

# create a vector
vector = np.random.rand(10)

# create a matrix
matrix = np.array(
    [[11, 14, 17],
     [23, 26, 26],
     [29, 32, 35]])

display(vector, vector.shape, matrix, matrix.shape)

array([0.92291489, 0.91670404, 0.91863772, 0.25026224, 0.3803684 ,
       0.18664402, 0.20974551, 0.65804184, 0.80463414, 0.6359579 ])

(10,)

array([[11, 14, 17],
       [23, 26, 26],
       [29, 32, 35]])

(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [32]:
# add a constant to each vector element
vector_add_10 = (vector + 10).round(2)

# multiply each vector element by a constant
vector_mul_2 = vector * 2

# find the square of each vector element
vector_sq = vector**2

display (vector_add_10, vector_mul_2, vector_sq)

array([10.62, 10.49, 10.46, 10.92, 10.65, 10.05, 10.38, 10.34, 10.29,
       10.45])

array([1.23182908, 0.985436  , 0.92805985, 1.8377945 , 1.29808835,
       0.10172667, 0.76674939, 0.68064434, 0.58040694, 0.90479555])

array([0.37935072, 0.24277103, 0.21532377, 0.84437215, 0.42125834,
       0.00258708, 0.14697616, 0.11581918, 0.08421805, 0.20466375])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 1х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [9]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [42]:
#multiply matrices B and A

result_matrix = B @ A
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

Результатом множення матриці розміром  𝑚×𝑛  на матрицю розміром  𝑛×𝑝  буде нова матриця розміром  𝑚×𝑝, отже множачи result_matrix розміром  2×2 на матрицю С розміром 2×1 отримаємо матрицю 2×1.

In [36]:
#multiply matrices result_matrix and C

result_matrix @ C

array([[0.5202],
       [0.2846]])

Множачи result_matrix розміром  2×2 на матрицю D розміром 2×2 отримаємо матрицю 2×2.

In [43]:
#multiply matrices result_matrix and D

result_matrix @ D

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [19]:
# transpose a matrix

result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [44]:
# transpose a vector

vector_t = vector.T

display(vector_t, vector_t.shape)

array([0.61591454, 0.492718  , 0.46402992, 0.91889725, 0.64904417,
       0.05086333, 0.38337469, 0.34032217, 0.29020347, 0.45239777])

(10,)

Спостереження: одновимірний вектор не змінив своєї структури після транспонування.

In [45]:
# expand dimensions of a vector

column_vector = np.expand_dims(vector, axis=1)

display(column_vector, column_vector.shape)

array([[0.61591454],
       [0.492718  ],
       [0.46402992],
       [0.91889725],
       [0.64904417],
       [0.05086333],
       [0.38337469],
       [0.34032217],
       [0.29020347],
       [0.45239777]])

(10, 1)

Спостереження: column_vector є двовимірним.

In [46]:
#transpose a column vector

column_vector_t = column_vector.T

column_vector_t, column_vector_t.shape

(array([[0.61591454, 0.492718  , 0.46402992, 0.91889725, 0.64904417,
         0.05086333, 0.38337469, 0.34032217, 0.29020347, 0.45239777]]),
 (1, 10))